import { NuqsAdapter } from 'nuqs/adapters/next/app'

import Header from '../../components/Header/index'
import './globals.css'

export const metadata = {
  description: 'Generated by Next',
  title: 'Next',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NuqsAdapter>
          <Header />
          {children}
        </NuqsAdapter>
      </body>
    </html>
  )
}
