import Header from '../../components/Header/index'
import './globals.css'

export const metadata = {
  description: 'Generated by Next',
  title: 'Next',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
