name: Build

on:
    pull_request:
        types: [opened, reopened, synchronize]
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
                  uses: pnpm/action-setup@v4
                  with:
                  version: 9
            - name: Use Node.js 20.x
                  uses: actions/setup-node@v4
                  with:
                  node-version: 20.x
                  cache: 'pnpm'
            - name: Install dependencies
                  run: pnpm install
            - name: Build
                  run: pnpm build
