name: Build

on:
    pull_request:
        types: [opened, reopened, synchronize]
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
            - run: pnpm install
            - run: pnpm build
